/**
 * Decode coverage for the COG types across our collections (and ones we're
 * likely to ingest). Two layers:
 *
 *  1. Real fixtures (collection-fixtures/, generated by generate.sh with GDAL):
 *     open each COG, fetch a tile, and assert the decoded RasterArray has a
 *     valid, self-consistent shape (toBandSeparate / toPixelInterleaved throw on
 *     a count/bands mismatch -- exactly what surfaced the Vermont LERC bug) and
 *     the correct interleaved band order. Each fixture burns band b with the
 *     constant (b+1)*10, so pixel 0 must be [10, 20, ...].
 *
 *  2. LERC layout mapping (mocked): this GDAL build can't write LERC, so the
 *     chunky-vs-planar mapping that broke on Vermont VTORTHO CLRIR is covered by
 *     driving the lerc codec with a stubbed lerc lib return.
 *
 * Collection -> type coverage:
 *   NAIP / Indiana  -> uint8  4-band chunky (RGBIR)
 *   KyFromAbove/RGB -> uint8  3-band chunky
 *   New Jersey      -> uint16 4-band chunky
 *   Vermont PAN     -> single-band
 *   Vermont CLRIR   -> 4-band chunky LERC (mocked layout test)
 */
import { resolve } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { SourceFile } from "@chunkd/source-file";
import { SourceHttp } from "@chunkd/source-http";
import { toBandSeparate, toPixelInterleaved } from "../src/array.js";
import { GeoTIFF } from "../src/geotiff.js";

const FIXTURE_DIR = resolve(import.meta.dirname, "collection-fixtures");

const FIXTURES = [
  { name: "uint8_4band_chunky_deflate", count: 4 }, // NAIP / Indiana RGBIR
  { name: "uint8_3band_chunky_deflate", count: 3 }, // KyFromAbove / RGB viz
  { name: "uint16_4band_chunky_deflate", count: 4 }, // New Jersey (16-bit)
  { name: "uint8_1band_deflate", count: 1 }, // single-band (PAN-shaped)
] as const;

async function openFixture(name: string): Promise<GeoTIFF> {
  const source = new SourceFile(resolve(FIXTURE_DIR, `${name}.tif`));
  return GeoTIFF.open({ dataSource: source, headerSource: source });
}

describe("collection COG decode (real fixtures)", () => {
  for (const { name, count } of FIXTURES) {
    it(`${name}: decodes to a valid, correctly-ordered RasterArray`, async () => {
      const tiff = await openFixture(name);
      const { array } = await tiff.fetchTile(0, 0);
      const { width, height } = array;

      // Shape must validate; a count/bands mismatch throws here (the Vermont bug).
      const bandSeparate = toBandSeparate(array);
      expect(bandSeparate.bands).toHaveLength(count);

      const interleaved = toPixelInterleaved(array);
      expect(interleaved.layout).toBe("pixel-interleaved");
      expect(interleaved.count).toBe(count);
      expect(interleaved.data.length).toBe(width * height * count);

      // Interleaved band order: burned values are 10, 20, 30, ...
      const expected = Array.from({ length: count }, (_, b) => (b + 1) * 10);
      expect(Array.from(interleaved.data.slice(0, count))).toEqual(expected);
    });
  }
});

// Real end-to-end LERC decode against a live public Vermont CLRIR COG
// (4-band, PlanarConfig=1, LERC). Opt-in (network): set COG_NETWORK_TESTS=1.
const VT_CLRIR_URL =
  "https://vtopendata-prd.s3.us-east-2.amazonaws.com/Imagery/_Tiles/VTORTHO/0_3M/CLRIR/2024/COGS/VT_510141_20240423.tif";

describe.skipIf(!process.env.COG_NETWORK_TESTS)(
  "real Vermont VTORTHO CLRIR (network, LERC PlanarConfig=1)",
  () => {
    it("decodes a real LERC tile to a valid pixel-interleaved RasterArray", async () => {
      const source = new SourceHttp(VT_CLRIR_URL);
      const tiff = await GeoTIFF.open({
        dataSource: source,
        headerSource: source,
      });
      const { array } = await tiff.fetchTile(5, 5);

      const interleaved = toPixelInterleaved(array);
      expect(interleaved.layout).toBe("pixel-interleaved");
      expect(interleaved.count).toBe(4);
      expect(interleaved.data.length).toBe(array.width * array.height * 4);
    }, 30000);
  },
);

describe("LERC codec layout mapping (regression: Vermont VTORTHO CLRIR)", () => {
  afterEach(() => vi.resetModules());

  async function decodeWithLerc(lercResult: unknown) {
    vi.doMock("lerc", () => {
      const mod = { load: vi.fn(async () => {}), decode: vi.fn(() => lercResult) };
      return { ...mod, default: mod };
    });
    const { decode } = await import("../src/codecs/lerc.js");
    return decode(new Uint8Array().buffer, {} as never);
  }

  it("chunky tile (single LERC band, dimCount>1) -> pixel-interleaved", async () => {
    // GDAL encodes PlanarConfig=1 multi-sample tiles this way; pixels has length
    // 1 while samplesPerPixel is 4 -- the shape that tripped the validator.
    const data = new Uint8Array([10, 20, 30, 40, 10, 20, 30, 40]);
    const result = await decodeWithLerc({ pixels: [data], dimCount: 4 });
    expect(result.layout).toBe("pixel-interleaved");
    expect((result as { data: Uint8Array }).data).toBe(data);
  });

  it("planar tile (dimCount=1, one array per band) -> band-separate", async () => {
    const bands = [new Uint8Array([10, 10]), new Uint8Array([20, 20])];
    const result = await decodeWithLerc({ pixels: bands, dimCount: 1 });
    expect(result.layout).toBe("band-separate");
    expect((result as { bands: Uint8Array[] }).bands).toHaveLength(2);
  });
});
